[{"row":1,
"column":1,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"row":1,
"column":2,
"status":"occupied",
"good":{"name": "Coca-cola","desiredTemperature":{"min":8,"max":12},"desiredLighting":100},
"temperature":20,"lighting":100},
{"row":1,
"column":3,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"row":1,
"column":4,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"row":2,
"column":1,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"row":2,
"column":2,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"row":2,
"column":3,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"row":2,
"column":4,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"row":3,
"column":1,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"row":3,
"column":2,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"row":3,
"column":3,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"row":3,
"column":4,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"row":4,
"column":1,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"row":4,
"column":2,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"row":4,
"column":3,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"row":4,
"column":4,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100}
]
