[{"x_coord":1,
"y_coord":1,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"x_coord":2,
"y_coord":1,
"status":"free",
"good":false,
"temperature":20,"lighting":100},
{"x_coord":4,
"y_coord":1,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"x_coord":5,
"y_coord":1,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"x_coord":1,
"y_coord":2,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"x_coord":2,
"y_coord":2,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"x_coord":4,
"y_coord":2,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"x_coord":5,
"y_coord":2,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"x_coord":1,
"y_coord":4,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"x_coord":2,
"y_coord":4,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"x_coord":4,
"y_coord":4,
"status":"occupied",
"good":{"name": "Coca-cola","desiredTemperature":{"min":8,"max":12},"desiredLighting":100},
"temperature": 20,
"lighting": 100},
{"x_coord":5,
"y_coord":4,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"x_coord":1,
"y_coord":5,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"x_coord":2,
"y_coord":5,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"x_coord":4,
"y_coord":5,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100},
{"x_coord":5,
"y_coord":5,
"status":"free",
"good":false,
"temperature": 20,
"lighting": 100}
]
